CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE PERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    DNO INT
);

INSERT INTO PERS (NAME, DNO) VALUES
('Kamal', 10),
('Ram', 20),
('Shyam', 10),
('Amit', 30),
('Ravi', 20);